apiVersion: apps/v1
kind: Deployment
metadata:
  name: source
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  labels:
    app: swir
    swir: source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swir
  template:
    metadata:
      labels:
        app: swir
    spec:
      containers:
      - name: client
        image: swir-example-java-source:v0.3.2
        env:
          - name: sidecar_hostname
            value: "127.0.0.1"
          - name: sidecar_port
            value: "50051"
          - name: produce_topic
            value: orders
          - name: client_database_name
            value: source_store

