apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor1
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  labels:
    app: swir
    swir: processor1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swir
  template:
    metadata:
      labels:
        app: swir
    spec:
      containers:
      - name: client
        image: swir-example-python-processor:v0.3.2
        env:
          - name: sidecar
            value: "127.0.0.1:50051"
          - name: subscribe_topic
            value: orders
          - name: publish_topic
            value: inventory
