apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor2
  annotations:
    "sidecar.jaegertracing.io/inject": "true"  
  labels:
    app: swir
    swir: processor2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swir
  template:
    metadata:
      labels:
        app: swir
    spec:
      containers:
      - name: client
        image: swir-example-java-processor:v3
        env:
          - name: sidecar_url
            value: "http://127.0.0.1:8080"
          - name: subscribe_topic
            value: inventory
          - name: producer_topic
            value: billing
          - name: server_port
            value: "8090"
