apiVersion: apps/v1
kind: Deployment
metadata:
  name: sink
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
  labels:
    app: swir
    swir: sink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swir
  template:
    metadata:
      labels:
        app: swir
    spec:
      containers:
      - name: client
        image: swir-example-python-sink:v0.3.1
        env:
          - name: sidecar
            value: "127.0.0.1:50051"
          - name: subscribe_topic
            value: shipments
          - name: client_database_name
            value: sink_store

