ip: "0.0.0.0"
http_port: 8080
grpc_port: 50051
internal_grpc_port: 50052

client_config:
  ip: "127.0.0.1"
  http_port: 8090
  grpc_port: 50053

tracing:
  open_telemetry:
    collector_address: "127.0.0.1"
    collector_port: "6831"
    service_name: processor2


#client_executable: "client.jar"
pubsub:
  kafka:
    - brokers: [kafka-1.kafka-headless.kafka.svc.cluster.local:9092]
      producer_topics:
        - producer_topic: processor3_kafka_red
          client_topic: billing
      consumer_topics: []                
      

  nats:
    - brokers:
        - nats://nats-client.nats.svc.cluster.local:4222
#         - nats://10.103.130.213:4222
      consumer_topics:
        - consumer_topic: processor2_nats_green
          consumer_group: swir
          client_topic: inventory
      producer_topics: []
      
  aws_kinesis: []

stores:  
  redis: []
  dynamodb: []  

