kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: swir-operator
subjects:
- kind: ServiceAccount
  name: swir-operator
  namespace: "swir-ns" # change to point to the namespace you installed your operator
roleRef:
  kind: ClusterRole
  name: swir-operator
  apiGroup: rbac.authorization.k8s.io
  

# kind: RoleBinding
# apiVersion: rbac.authorization.k8s.io/v1
# metadata:
#   name: swir-operator
# subjects:
# - kind: ServiceAccount
#   name: jaeger-operator
# roleRef:
#   kind: Role
#   name: swir-operator
#   apiGroup: rbac.authorization.k8s.io
