version: '3.7'
services:
  swir:
    networks:
      - swir-net
    image: swir/swir:v0.3.2-perf
    ports:
      - "8080:8080"
      - "8443:8443"
      - "50051:50051"
    
  swir-kafka-sink1:
    networks:
      - swir-net
    image: swir-kafka-sink:v0.3.2
    environment:
      - bootstrap_servers=kafka:9094
      - sink_consumer_topic=Request
      - sink_consumer_group=swir
      - sink_producer_topic=Response
    depends_on: 
      - "swir"
      
  swir-kafka-sink2:
    networks:
      - swir-net
    image: swir-kafka-sink:v0.3.2
    environment:
      - bootstrap_servers=kafka:9094
      - sink_consumer_topic=Request2
      - sink_consumer_group=swir
      - sink_producer_topic=Response2
    depends_on: 
      - "swir"      


      
  swir-nats-sink:
    networks:
      - swir-net
    image: swir-nats-sink:v0.3.2
    environment:
      - bootstrap_servers=nats://nats:4222
      - subscribe_topic=Request
      - response_topic=Response
    depends_on: 
      - "swir"
      
  swir-nats-sink2:
    networks:
      - swir-net
    image: swir-nats-sink:v0.3.2
    environment:
      - bootstrap_servers=nats://nats:4222
      - subscribe_topic=Request2
      - response_topic=Response2
    depends_on: 
     - "swir"
     
  swir-java-client:
    networks:
      - swir-net
    image: swir-java-client:v0.3.2
    environment:
      - sidecar_url=h2://swir:8080/publish
      - bootstrap_servers=kafka:9094
      - consumer_topic=ResponseNoSidecar
      - consumer_group=swir
      - producer_topic=RequestNoSidecar
    depends_on:
      - "swir"
networks:
  swir-net:
    external:
      name: docker_swir-net
