
ip: "0.0.0.0"
http_port: 8080
grpc_port: 50051
internal_grpc_port: 50052

client_config:
  ip: order-processor
  http_port: 8090
  grpc_port: 50053

tracing:
  open_telemetry:
    collector_address: swir-example-logger
    collector_port: 6831
    service_name: pubsub-store-example
    
#client_executable: "client.jar"
pubsub:
  kafka:
    - brokers: [kafka:9094]
      consumer_topics:
        - consumer_topic: processor1_kafka_blue
          consumer_group: swir
          client_topic: orders
      producer_topics: []

  nats:
    - brokers:
        - nats://nats:4222
      producer_topics:
        - producer_topic: processor2_nats_green
          client_topic: inventory
      consumer_topics: []
      
  aws_kinesis: []
  
stores:  
  redis: []
  dynamodb: []



