FROM rust:latest as swir_builder
WORKDIR /swir
COPY src ./src
COPY grpc_api ./grpc_api
COPY Cargo.toml ./
COPY Cargo.lock ./
COPY build.rs ./
COPY rustfmt.toml ./
COPY deny.toml ./

RUN rustup component add rustfmt 
RUN cargo build --release --all-features