# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import client_api_pb2 as client__api__pb2


class ClientApiStub(object):
  """The definition of API exposed by Sidecar.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Publish = channel.unary_unary(
        '/swir.ClientApi/Publish',
        request_serializer=client__api__pb2.PublishRequest.SerializeToString,
        response_deserializer=client__api__pb2.PublishResponse.FromString,
        )
    self.PublishBiStream = channel.stream_stream(
        '/swir.ClientApi/PublishBiStream',
        request_serializer=client__api__pb2.PublishRequest.SerializeToString,
        response_deserializer=client__api__pb2.PublishResponse.FromString,
        )
    self.Subscribe = channel.unary_stream(
        '/swir.ClientApi/Subscribe',
        request_serializer=client__api__pb2.SubscribeRequest.SerializeToString,
        response_deserializer=client__api__pb2.SubscribeResponse.FromString,
        )


class ClientApiServicer(object):
  """The definition of API exposed by Sidecar.
  """

  def Publish(self, request, context):
    """Publish message to a topic/queue
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PublishBiStream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Subscribe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ClientApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Publish': grpc.unary_unary_rpc_method_handler(
          servicer.Publish,
          request_deserializer=client__api__pb2.PublishRequest.FromString,
          response_serializer=client__api__pb2.PublishResponse.SerializeToString,
      ),
      'PublishBiStream': grpc.stream_stream_rpc_method_handler(
          servicer.PublishBiStream,
          request_deserializer=client__api__pb2.PublishRequest.FromString,
          response_serializer=client__api__pb2.PublishResponse.SerializeToString,
      ),
      'Subscribe': grpc.unary_stream_rpc_method_handler(
          servicer.Subscribe,
          request_deserializer=client__api__pb2.SubscribeRequest.FromString,
          response_serializer=client__api__pb2.SubscribeResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'swir.ClientApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
