version: '3.7'
# Sidecars layer. All sidecars are already deployed.
services:
  swir-example-si-configurator:
    networks:
      - swir-si
    image: swir-example-si-configurator:v0.3.2
#    command: ["/bin/bash","-c","cp /config/* swir_config/ ; cp /certificates/* certs/"]
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config
      - type: volume
        source: certs
        target: /certs
        
  swir-example-logger:
    networks:
      - swir-si
    image: jaegertracing/all-in-one:1.18
    depends_on:
      - swir-example-si-configurator
#    command: ["/bin/bash","-c","cp /config/* swir_config/ ; cp /certificates/* certs/"]
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "9411"
      - "5775/udp"
      - "6831/udp"
      - "6832/udp"
      - "5778"
      - "16686:16686"
      - "14268"
      - "4250"
              


  orchestator_sidecar:
    networks:
      - swir-si
    image: swir/swir:v0.3.2
    depends_on:
      - swir-example-si-configurator
      - swir-example-logger
    ports:
      - "8080"
      - "8443"
      - "50051"
      - "50052"
    environment:
      - swir_config_file=/swir_config/swir_source.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config
      - type: volume
        source: certs
        target: /certs                



  books_sidecar:
    networks:
      - swir-si
    image: swir/swir:v0.3.2
    depends_on:
      - swir-example-si-configurator
      - swir-example-logger      
    ports:
      - "8080"
      - "8443"
      - "50051"
      - "50052"
    environment:
      - swir_config_file=/swir_config/swir_books_service.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config
      - type: volume
        source: certs
        target: /certs        


  magazinges_sidecar:
    networks:
      - swir-si
    image: swir/swir:v0.3.2
    depends_on:
      - swir-example-si-configurator
      - swir-example-logger      
    ports:
      - "8080"
      - "8443"
      - "50051"
      - "50052"
    environment:
      - swir_config_file=/swir_config/swir_magazine_service.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config
      - type: volume
        source: certs
        target: /certs

  books:
    networks:
      - swir-si
    image: swir-example-si-python-http-server:v0.3.2
    depends_on:
     - books_sidecar
    environment:
      - port=8090

  magazines:
    networks:
      - swir-si
    image: swir-example-si-python-http-server:v0.3.2
    depends_on:
      - magazinges_sidecar
    environment:
      - port=8090

  orchestrator_app:
    networks:
      - swir-si
    image: swir-example-si-python-grpc-client:v0.3.2
    depends_on:
     - orchestator_sidecar
    environment:
      - sidecar=orchestator_sidecar:50051
      - service_names=books,magazines

        
volumes:
  swir_config:
  certs:
networks:
  swir-si:

