version: '3.7'
# Sidecars layer. All sidecars are already deployed.
services:
  swir-example-configurator:
    networks:
      - swir-net
    image: swir-example-configurator:v3
    command: ["/bin/bash","-c","cp /config/* swir_config/"]
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config

  swir-example-logger:
    networks:
      - swir-net
    image: jaegertracing/all-in-one:1.18
#    command: ["/bin/bash","-c","cp /config/* swir_config/ ; cp /certificates/* certs/"]
    depends_on:
      - swir-example-configurator
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "9411"
      - "5775/udp"
      - "6831/udp"
      - "6832/udp"
      - "5778"
      - "16686:16686"
      - "14268"
      - "4250"        

# step 1 
# Java gRCP
  order-generator-sidecar:
    networks:
      - swir-net
    image: swir/swir:v3
    depends_on:
      - swir-example-configurator
      - swir-example-logger
    ports:
      - "8080"
      - "8443"
      - "50051"
    environment:
      - swir_config_file=/swir_config/swir_source.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config

# step 2     
# python gRPC
  order-processor-sidecar:
    networks:
      - swir-net
    image: swir/swir:v3
    depends_on:
      - swir-example-configurator
      - swir-example-logger      
    ports:
      - "8080"
      - "8443"
      - "50051"
    environment:
      - swir_config_file=/swir_config/swir_processor_1.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config

# step 3           
# Java SpringBoot and REST        
  inventory-processor-sidecar:
    networks:
      - swir-net
    image: swir/swir:v3
    depends_on:
      - swir-example-configurator
      - swir-example-logger      
    ports:
      - "8080"
      - "8443"
      - "50051"
    environment:
      - swir_config_file=/swir_config/swir_processor_2.yaml
    volumes:
      - type: volume
        source: swir_config
        target: /swir_config


# step 4           
# python gRPC              
  billing-processor-sidecar:
    networks:
      - swir-net
    image: swir/swir:v3
    depends_on:
      - swir-example-configurator
      - swir-example-logger      
    ports:
      - "8080"
      - "8443"
      - "50051"
    environment:
      - swir_config_file=/swir_config/swir_processor_3.yaml

    volumes:
      - type: volume
        source: swir_config
        target: /swir_config


# step 5
# Python gRPC
  shipments-sink-sidecar:
    networks:
      - swir-net
    image: swir/swir:v3
    depends_on:
      - swir-example-configurator
      - swir-example-logger
    ports:
      - "8080"
      - "8443"
      - "50051"
    environment:
      - swir_config_file=/swir_config/swir_sink.yaml

    volumes:
      - type: volume
        source: swir_config
        target: /swir_config                
        
volumes:
  swir_config:
networks:
  swir-net:
    external:
      name: docker_swir-net
